import { Meteor } from 'meteor/meteor'
import { Mongo } from 'meteor/mongo'
import { Collections, DEFAULT_AWARDS_NAMES, DEFAULT_CATEGORY_NAMES } from './enums'

export interface Award {
	_id?: string
	/** Name of awards ceremony. */
	name: string,
	/** IDs of categories belonging to this awards ceremony. */
	categories: string[],
	submissionsOpen?: number,
	submissionsClose?: number,
	active: boolean
}

export const Awards = new Mongo.Collection<Award>(Collections.AWARDS)

if (Meteor.isServer) {
	Meteor.publish(Collections.AWARDS, function awardsPublictaion () {
		return Awards.find()
	})
}

export const DEFAULT_AWARDS: Award[] = [
	{
		name: DEFAULT_AWARDS_NAMES.NASTA,
		categories: [],
		active: true
	},
	{
		name: DEFAULT_AWARDS_NAMES.PEOPLES_CHOICE,
		categories: [],
		active: false
	}
]

export const DEFAULT_CATEGORIES_FOR_AWARDS: { [awards: string]: string[] } = {
	[DEFAULT_AWARDS_NAMES.NASTA]: [
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_BEST_BROADCASTER,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_JISC,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_BEST_DRAMATIC_PERFORMANCE,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_BEST_ON_SCREEN_TALENT,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_STATION_MARKETING,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_TECHNICAL_ACHIEVEMENT,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_FRESHERS_COVERAGE,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_ANIMATION,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_NEWS_AND_CURRENT_AFFAIRS,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_MARS_ELKINS_EL_BROGY,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_WRITING,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_LIVE_BROADCAST,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_CINEMATOGRAPHY,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_LIGHT_ENTERTAINMENT,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_TITLE_SEQUENCE,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_COMEDY,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_DRAMA,
		DEFAULT_CATEGORY_NAMES.DOCUMENTARY_AND_FACTUAL,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_SPORT,
		DEFAULT_CATEGORY_NAMES.NaSTA_AWARDS_POST_PRODUCTION_AWARD
	],
	[DEFAULT_AWARDS_NAMES.PEOPLES_CHOICE]: [
		DEFAULT_CATEGORY_NAMES.PCAs_OPEN,
		DEFAULT_CATEGORY_NAMES.PCAs_LIVE_BROADCAST,
		DEFAULT_CATEGORY_NAMES.PCAs_CONTENT_INNOVATION,
		DEFAULT_CATEGORY_NAMES.PCAs_TECHNICAL_INNOVATION,
		DEFAULT_CATEGORY_NAMES.PCAs_VISUAL_CREATIVITY_AND_QUALITY,
		DEFAULT_CATEGORY_NAMES.PCAs_BEST_ON_SCREEN_TALENT,
		DEFAULT_CATEGORY_NAMES.PCAs_UN_SUNG_HERO,
		DEFAULT_CATEGORY_NAMES.PCAs_STATION_OF_THE_YEAR
	]
}
